### ISSUE TITLE
Fix: image size mayhem (>> implement global image size constraint)

### ISSUE THREAD

**Issue by uschtwill** [uschtwill/rails_rss_reader#15]

**Comment by uschtwill** [comment]
fixed using the following in the application.css:

``` css
img {
  max-width: 100%;
  max-height: auto;
} 
```

works like a charm....
